#!/bin/sh
#
# Wrapper script for openoffice
#
# (C) Peter 'Nidd' Novodvorsky, 2001,2002
#     Modified by Chris Halls

# This program is free software; you can redistribute it and/or modify         
# it under the terms of the GNU General Public License as published by         
# the Free Software Foundation; either version 2 of the License, or            
# (at your option) any later version.                                          
#                                                                             
# This program is distributed in the hope that it will be useful,              
# but WITHOUT ANY WARRANTY; without even the implied warranty of               
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU             
# General Public License for more details.                                     
#                                                                             
# You should have received a copy of the GNU General Public License            
# along with this program; if not, write to the Free Software                  
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA      

# Unset SESSION_MANAGER if gnome-session is the session manager
# See http://www.openoffice.org/issues/show_bug.cgi?id=4494
SMPID=`echo $SESSION_MANAGER | sed --quiet "s,local.*/,,p"`

if [ -n "$SMPID" ]; then
  if ps -p$SMPID -ocmd --no-heading | grep -q "^[^ ]*gnome-session"; then
    echo "Gnome session manager detected - session management disabled"
    unset SESSION_MANAGER
  fi
fi

if [ ! -d ~/.openoffice ]; then
  echo running openoffice setup...
  if ! /usr/lib/openoffice/program/setup -R:/etc/openoffice/autoresponse.conf ;then
    echo setup failed.. abort
  fi
fi

if [ -x ~/.openoffice/soffice ]; then
  ~/.openoffice/soffice "$@"
else
  # Problem.  Try to diagnose possible causes
  echo OpenOffice.org could not be started - ~/.openoffice/soffice is not available
  if [ -f ~/.sversionrc ]; then
    echo You appear to already have an older verion.  Please remove these entries
    echo from ~/.sversionrc and try again.  You may also need to remove ~/.openoffice
    echo if there is an incomplete installation there.
    echo Contents of .sversionrc:
    cat ~/.sversionrc
  fi
fi
