#! /usr/bin/python3

import os
import sys

prog = os.path.join("/usr/bin", os.path.basename(sys.argv[0]))
new_argv = []

for arg in sys.argv[1:]:
    if arg.startswith("-flto=") or arg == "-ffat-lto-objects":
        continue
    new_argv.append(arg)

try:
    os.execv(prog, new_argv)
except FileNotFoundError:
    print("unable to execute:", prog, new_argv)
    sys.exit(1)
