#! /bin/bash

basedir=debian/l10n

_convert2po()
{
    local lc=${1#*_*}
    lc=${lc%*.sdf}

    rm -rf $basedir/$lc
    mkdir -p $basedir/$lc
    $basedir/../splitgsi $basedir/export/GSI_$lc.sdf $basedir/$lc
    cd $basedir/$lc
    for f in *.sdf; do
	d=${f%*.sdf}
	mkdir -p ../$d $d
	if [ "$lc" = en-US ]; then
	    oo2po -P --progress=names --multifile=onefile -o ../$d/$d.pot $f
	else
	    oo2po --progress=names --multifile=onefile -l $lc -o ../$d/$lc.po $f
	fi
	rmdir $d
    done
    cd - >/dev/null
    rm -rf $basedir/$lc
}

_convert2oo()
{
    local lc=$1
    [ "$lc" = en-US ] && return
    rm -rf $basedir/$lc
    mkdir -p $basedir/$lc
    $basedir/../splitgsi $basedir/export/GSI_$lc.sdf $basedir/$lc
    cd $basedir/$lc
    for f in *.sdf; do
        d=${f%*.sdf}
	[ -f ../$d/$lc.po ] || continue
        echo $d
	cp -p $d.sdf $d.oo
        po2oo --multifile=onefile -l $lc -i ../$d/$lc.po -o ${f}2 -t $d.oo
	rm -f $d.oo
    done
    cd - >/dev/null
}

convert=`basename $0`

for lc in "$@"; do
    echo $convert $lc
    _$convert $lc
done
