usr/lib/openoffice/sdk/linux/bin/cppumaker
usr/lib/openoffice/sdk/linux/bin/idlc
usr/lib/openoffice/sdk/linux/bin/idlcpp
usr/lib/openoffice/sdk/linux/bin/javamaker
usr/lib/openoffice/sdk/linux/bin/rdbmaker
usr/lib/openoffice/sdk/linux/bin/regcompare
usr/lib/openoffice/sdk/linux/bin/regmerge
usr/lib/openoffice/sdk/linux/bin/regview
usr/lib/openoffice/sdk/linux/bin/uno
usr/lib/openoffice/sdk/linux/bin/xml2cmp
usr/lib/openoffice/sdk/linux/lib/libprot_uno_uno.so
usr/lib/openoffice/sdk/idl/* usr/share/idl/openoffice
usr/lib/openoffice/sdk/include/* usr/include/openoffice
usr/lib/openoffice/sdk/xml/* usr/share/xml/openoffice
usr/lib/openoffice/sdk/configure
usr/lib/openoffice/sdk/configure.pl
usr/lib/openoffice/sdk/setsdkenv_unix.in
usr/lib/openoffice/program/libcppu.so
usr/lib/openoffice/program/libcppuhelper3gcc3.so
usr/lib/openoffice/program/libcppuhelpergcc3.so
usr/lib/openoffice/program/libicudata.so
usr/lib/openoffice/program/libicui18n.so
usr/lib/openoffice/program/libicule.so
usr/lib/openoffice/program/libicuuc.so
usr/lib/openoffice/program/libreg.so
usr/lib/openoffice/program/librmcxt.so
usr/lib/openoffice/program/libsal.so
usr/lib/openoffice/program/libsalhelper3gcc3.so
usr/lib/openoffice/program/libsalhelpergcc3.so
usr/lib/openoffice/program/libstore.so
usr/lib/openoffice/sdk/settings

