#!/bin/sh

set -e

for FILE in doogie-build-system; do
  chmod 755 debian/$FILE
done

for FILE in fix.source.patch \
            getglibcversion \
            patch.apply \
            patch.unapply \
            source.patch \
            source.unpack \
            unfix.source.patch \
            vars*; do
  chmod 755 debian/scripts/$FILE
done

for FILE in oo-xvfb-run; do
  chmod 755 debian/local/scripts/$FILE
done

# vim:set ai et sts=2 sw=2 tw=0:
