#!/bin/sh

set -e

cd debian

for FILE in scripts/vars* \
	    scripts/installoverrides \
	    scripts/xcftobmp \
	    scripts/oo-xvfb-run \
            local/openoffice-*-lang 
do
  chmod 755 $FILE
done

# vim:set ai et sts=2 sw=2 tw=0:
