#!/bin/sh

echo "====== Preparing the SDK environment ======"
cd /usr/lib/libreoffice/sdk
. ./setsdkenv_unix.sh

d=`pwd`

echo "====== Building C++ example DocumentLoader ====== "
cd $d/examples/cpp/DocumentLoader
make clean
make

echo "====== Building C++ example counter ====== "
cd $d/examples/cpp/counter
make clean
make
echo "====== Running countermain.run ======"
make countermain.run

# This needs unowinreg.dll which is in -dev, but only for i386/amd64...
if [ -e /usr/lib/libreoffice/sdk/classes/win/unowinreg.dll ]; then
	echo "====== Building Java DocumentHandling example ======"
	cd $d/examples/java/DocumentHandling
	make clean
fi

