#!/bin/bash
# autopkgtest check: Run smoketest against an installed version of LibreOffice
# (c) 2018 Software in the Public Interest, Inc.
# Authors: Rene Engelhard <rene@debian.org>

set -e
set -E

SRCDIR=`pwd`
CHECK_PARALLELISM=1
if [ -n "$AUTOPKGTEST_TMP" ]; then
	TMP=`mktemp -q -p $AUTOPKGTEST_TMP`
	WORKDIR=`mktemp -q -d -p $AUTOPKGTEST_TMP`
else
	TMP=`mktemp -q`
	WORKDIR=`mktemp -q -d`
fi

function unapply() {
	cd $SRCDIR
	echo
	echo "====== Unapplying the patches ======"
	patch -p1 -R < ./debian/tests/patches/cppunit-standalone.diff
	patch -p1 -R < ./debian/tests/patches/smoketest-standalone.diff
	patch -p0 -R < ./debian/tests/patches/smoketest-disable-extension-tests.diff
}

trap "unapply" ERR

echo
echo "====== Patching the tree to only build the smoketest unittest against an existing installation ======"
patch -p1 < ./debian/tests/patches/cppunit-standalone.diff
patch -p1 < ./debian/tests/patches/smoketest-standalone.diff
patch -p0 < ./debian/tests/patches/smoketest-disable-extension-tests.diff

echo
echo "====== Enabling core dumps ======"
# yes, we want core dumps and stack traces
ulimit -c unlimited || true

OOO_TEST_SOFFICE="${1:-path:/usr/lib/libreoffice/program/soffice}"

echo
echo "====== Starting smoketest with ${CHECK_PARALLELISM} job against ${OOO_TEST_SOFFICE} ======"

export PARALLELISM=$CHECK_PARALLELISM

export LD_LIBRARY_PATH=/usr/lib/libreoffice/program:$LD_LIBRARY_PATH
cd smoketest && make \
    OOO_TEST_SOFFICE=${OOO_TEST_SOFFICE} \
    subsequentcheck INSTDIR=/usr/lib/libreoffice verbose=t

cd $SRCDIR

unapply

