#!/bin/bash
# autopkgtest check: Run smoketest against an installed version of LibreOffice
# (c) 2018 Software in the Public Interest, Inc.
# Authors: Rene Engelhard <rene@debian.org>

set -e
set -E

SRCDIR=`pwd`
WORKDIR=`mktemp -d`
CHECK_PARALLELISM=1

function unapply() {
	cd $SRCDIR
	echo "====== Unapplying the patches ======"
	patch -p1 -R < ./debian/tests/patches/smoketest-standalone.diff
	patch -p0 -R < ./debian/tests/patches/smoketest-disable-extension-tests.diff
}

trap "unapply" ERR

echo "====== Patching the tree to only build the smoketest unittest against an existing installation ======"
patch -p1 < ./debian/tests/patches/smoketest-standalone.diff
patch -p0 < ./debian/tests/patches/smoketest-disable-extension-tests.diff

OOO_TEST_SOFFICE="${1:-path:/usr/lib/libreoffice/program/soffice}"

echo
echo
echo "====== Enabling core dumps ======"
# yes, we want core dumps and stack traces
ulimit -c unlimited

echo "====== Building LO and the tests ======"
# set nocheck to not try make check here right now
old_DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS"
export DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS nocheck"
./debian/rules build-arch
export DEB_BUILD_OPTIONS=$old_DEB_BUILD_OPTIONS

echo "====== Starting smoketest with ${CHECK_PARALLELISM} job against ${OOO_TEST_SOFFICE} ======"

export PARALLELISM=$CHECK_PARALLELISM
# the smoketest is a cppunit test. build-arch does --without-cppunit
sed -i 's/export ENABLE_CPPUNIT=.*/export ENABLE_CPPUNIT=TRUE/' config_host.mk
sed -i 's/export SYSTEM_CPPUNIT=.*/export SYSTEM_CPPUNIT=TRUE/' config_host.mk
sed -i 's/export CPPUNIT_CFLAGS=.*/export CPPUNIT_CFLAGS=$(gb_SPACE)/' config_host.mk
sed -i 's/export CPPUNIT_LIBS=.*/export CPPUNIT_LIBS=$(gb_SPACE) -lcppunit/' config_host.mk

cd smoketest && make -rk \
    OOO_TEST_SOFFICE=${OOO_TEST_SOFFICE} \
    CppunitTest_smoketest INSTDIR=/usr/lib/libreoffice verbose=t

cd $SRCDIR

unapply

