#!/bin/bash
# autopkgtest check: Install a test extension (as smoketest would do)
# (c) 2017 Software in the Public Interest, Inc.
# Authors: Rene Engelhard <rene@debian.org>

set -e
set -E

if [ -n "$ADTTMP" ]; then
        TMP=`mktemp -q -p $ADTTMP`
else
        TMP=`mktemp -q`
fi

# does it install fine?
unopkg add -v /usr/share/libreoffice/TestExtension.oxt

# does it list? For whatever reason unopkg leaves a stale .lock behind when
# doing this grep directly on the output so do it on a tmpfile
unopkg list | tee $TMP
grep -q org.libreoffice.smoketest.TestExtension $TMP || exit 1
rm $TMP

# does it remove?
unopkg remove -v org.libreoffice.smoketest.TestExtension


