.TH oopadmin "1" "April 2002" "OpenOffice.org 1.0.1" "User Commands"
.SH "Name"
oopadmin \- Printer and font administration tool for OpenOffice.org
.SH SYNOPSIS
.B oopadmin
.SH DESCRIPTION
oopadmin is a tool belonging to the OpenOffice.org office suite.

With oopadmin, you can tune some options for OpenOffice.org.
Even as a "normal" user, you can add fonts which should be used by
OpenOffice.org and you can add a new printer or tune your printer
configuration.

After doing that, OpenOffice.org has to be restarted to let the
settings take effect.

You also can print a test page to test if your printer configuration
is working.

.SS "Generic options:"
There are no command line options
.SH SEE ALSO
.BR openoffice (1)
.SH AUTHOR
This manual page was created newly by Rene Engelhard
<rene@openoffice.org> for the Debian GNU/Linux Distribution, because the original package does not have one.
