.TH openoffice "1" "April 2002" "OpenOffice.org 1.0.1" "User Commands"
.SH "Name"
openoffice \- OpenOffice.org office suite
.SH SYNOPSIS
.B openoffice [-display DISPLAYNAME] <filename>
.br
.B oocalc
.br
.B oodraw
.br
.B ooimpress
.br
.B oomath
.br
.B oowriter

.SH DESCRIPTION
OpenOffice.org is a fully featured office suite for the daily use with all
features you'd normally expect in a office suite.

This script runs OpenOffice with the arguments <args> given on the command line

There are also some wrapper scripts in /usr/bin which are calling the "normal"
openoffice script and runs the wanted OpenOffice.org module

.SS "Generic options:"
.TP
\fB<filename>\fB
These args are passed directly to the real start binary. It mostly contains the
file name which should be opened directly with starting OpenOffice.org.
.SH SEE ALSO
.BR oopadmin (1)
.SH AUTHOR
This manual page was created newly by Rene Engelhard <rene@openoffice.org> for
the Debian GNU/Linux Distribution, because the original package does not have
one.
