#!/usr/bin/perl

open(SUBSTVARS, "debian/openoffice.org-bin.substvars");

while(<SUBSTVARS>) {
	if(/shlibs/) {
		s/shlibs:Depends=//;
		s/,/\n/g;
		s/(.*)\(.*\)/\1/g;
		s/ //g;
		s/\|xlibs//g;
		print;	
	}
}
