#!/bin/bash
SCRIPTPATH=`readlink -f $0`
SCRIPTDIR=`dirname $SCRIPTPATH`
PATCHDIR=`readlink -f $SCRIPTDIR/../patches`
TMPDIR=`mktemp -d`
for commit in `git log -100 --pretty=%H`
do
    git format-patch --stdout -1 $commit > $TMPDIR/$commit
    if test -n "`grep DebianPatchName: $TMPDIR/$commit`"
    then
        PATCHNAME=`grep DebianPatchName: $TMPDIR/$commit|sed -e 's/^.*DebianPatchName: //'`
        grep -v DebianPatchName: $TMPDIR/$commit |grep -v ^From\  |grep -v ^index\ > $PATCHDIR/$PATCHNAME
        echo "Updating $PATCHNAME"
    fi
done
rm -rf $TMPDIR
