#!/bin/sh

pkg=$1
v=$2

for m in artwork base bootstrap calc components extensions extras \
	filters help impress l10n libs-core libs-extern libs-extern-sys \
	libs-gui postprocess sdk testing ure writer; do \
	if echo $pkg | grep -q $m; then
		if [ "$m" = "l10n" -o "$m" = "help" ]; then
			continue;
		fi
		install_cls="$m"
	fi
	if echo $pkg | grep -q l10n; then
		install_cls="$install_cls l10n"
	fi
	if echo $pkg | grep -q help; then
		install_cls="$install_cls help"
	fi
	if echo $pkg | grep -q style; then
		install_cls="$install_cls artwork"
	fi
	if [ "$pkg" = "libreoffice-common" -o "$pkg" = "libreoffice-core" ]; then
		install_cls="$install_cls components"
	fi
	if [ "$pkg" = "libreoffice-common" ]; then
		install_cls="$install_cls extras"
	fi
	if [ "$pkg" = "libreoffice-common" -o "$pkg" = "libreoffice-core" ] || \
	     echo "$pkg" | grep -q filter; then
		install_cls="$install_cls filters"
	fi
	if [ "$pkg" = "libreoffice-core" ]; then
		install_cls="$install_cls libs-core libs-extern libs-extern-sys libs-gui"
	fi
	if [ "$pkg" = "libreoffice-dev" -o "$pkg" = "libreoffice-dev-doc" ]; then
		install_cls="$install_cls sdk"
	fi
	if [ "$pkg" = "python-uno" ] || [ "$pkg" = "uno-libs3" ]; then
		install_cls="$install_cls ure"
	fi
	if [ "$pkg" = "libreoffice-officebean" ]; then
		install_cls="$install_cls components"
	fi
	if [ "$pkg" = "mozilla-libreoffice" ]; then
		install_cls="$install_cls components"
	fi
 	if [ "$pkg" = "libreoffice-ogltrans" ]; then
		install_cls="$install_cls impress"
	fi
	if [ "$pkg" = "libreoffice-wiki-publisher" -o \
	     "$pkg" = "libreoffice-report-builder" -o \
	     "$pkg" = "libreoffice-report-builder-bin" -o \
	     "$pkg" = "libreoffice-presentation-minimizer" -o \
	     "$pkg" = "libreoffice-presenter-console" -o \
	     "$pkg" = "libreoffice-pdfimport" -o \
	     "$pkg" = "libreoffice-mysql-connector" ]; then
		install_cls="$install_cls extensions"
	fi
	if [ "$pkg" = "ttf-opensymbol" ]; then
		install_cls="$install_cls extras"
	fi
	if [ "$pkg" = "libreoffice-gtk" -o "$pkg" = "libreoffice-kde" ]; then
		install_cls="$install_cls libs-gui"
	fi
	if [ "$pkg" = "libreoffice-gnome" -o "$pkg" = "libreoffice-kab" -o \
	     "$pkg" = "libreoffice-evolution" ]; then
		install_cls="$install_cls libs-core"
	fi

	for c in $install_cls; do
		# we need to extract them from the tarball as we can't use them
		# from the tree. Due to the path the same it only gets the last
		# one unpacked there.
		tar xfvj sources/libreoffice-$m-$v.tar.bz2 \
			libreoffice-$m-$v/ChangeLog
		mkdir -p debian/$pkg/usr/share/doc/$pkg
		install -m644 libreoffice-$m-$v/ChangeLog \
			debian/$pkg/usr/share/doc/$pkg/changelog.$m
		rm -rf libreoffice-$m-$v
	done
done
