#!/bin/bash
SCRIPTPATH=`readlink -f $0`
SCRIPTDIR=`dirname $SCRIPTPATH`
PATCHDIR=`readlink -f $SCRIPTDIR/../patches`
TMPDIR=`mktemp -d`
git checkout -b $1 $2
for patch in `grep -v ^# $PATCHDIR/series`
do
    echo "$patch"
    if test -z "`grep ^From: $PATCHDIR/$patch`" -a -z "`grep ^AuthorDate: $PATCHDIR/$patch`"
    then
            echo "From: Debian LibreOffice Maintainers <debian-openoffice@lists.debian.org>" > $TMPDIR/$patch
            echo "Date: `date -R`" >> $TMPDIR/$patch
            echo "Subject: $patch" >> $TMPDIR/$patch
    fi
    cat $PATCHDIR/$patch >> $TMPDIR/$patch
    git am --abort || true
    git am $TMPDIR/$patch && git log -1 HEAD --pretty=%B > $TMPDIR/msg && echo "\nDebianPatchName: $patch" >> $TMPDIR/msg && git commit --amend -F $TMPDIR/msg || true
done
rm -rf $TMPDIR
