#!/bin/sh

set -e

for FILE in debian/scripts/installoverrides \
	    debian/scripts/xcftobmp \
	    debian/scripts/gen_lib_list \
	    debian/scripts/move-if-change \
	    debian/scripts/aot-compile \
	    ooo-build/configure \
	    ooo-build/bin/[a-z]* \
	    ooo-build/patches/apply.pl
do
  chmod 755 $FILE
done

# vim:set ai et sts=2 sw=2 tw=0:
