#!/bin/bash
CURDIR=`readlink -f .`
TMPDIR=`mktemp -d`
BRANCH=feature/unitymenus-quantal
git clone $1 $TMPDIR/core
cd $TMPDIR/core
git checkout $BRANCH
git rebase $2
git log -1 $BRANCH > $CURDIR/patches/unitymenus.diff
git diff --stat $2 $BRANCH >> $CURDIR/patches/unitymenus.diff
git diff $2 $BRANCH >> $CURDIR/patches/unitymenus.diff
cd $CURDIR
rm -rf $TMPDIR
