#!/bin/bash
CURDIR=`readlink -f .`
TMPDIR=`mktemp -d`
git clone $1 $TMPDIR/core
cd $TMPDIR/core
git checkout feature/unitymenus
git rebase $2
git log -1 feature/unitymenus > $CURDIR/patches/unitymenus.diff
git diff --stat $2 feature/unitymenus >> $CURDIR/patches/unitymenus.diff
git diff $2 feature/unitymenus >> $CURDIR/patches/unitymenus.diff
cd $CURDIR
rm -rf $TMPDIR
