#!/usr/bin/perl

use Gimp qw(:auto );;


$in_name=$ARGV[0];
$out_name=$ARGV[0];
$out_name =~ s/xcf$/bmp/;

Gimp::init;


$img = Gimp->xcf_load(0,$in_name, $in_name);
$layer = $img->flatten;
file_bmp_save(NON_INTERACTIVE, $layer, $out_name, $out_name);
gimp_image_delete($img);
Gimp::end;
